export const showZones = (state) => state.main.zones
export const showZoneId = (state) => state.main.zoneId
export const showRams = (state) => state.main.rams
export const showRoms = (state) => state.main.roms
export const showFinances = (state) => state.main.finances
export const showDetails = (state) => state.main.details
export const showFilters = (state) => state.main.filters
export const showPartialFilters = (state) => state.main.partialFilters;
export const showPages = (state) => state.main.pages;